<?php
/**
 * Store Commander
 *
 * @category administration
 * @author Store Commander - support@storecommander.com
 * @version 2015-09-15
 * @uses Prestashop modules
 * @since 2009
 * @copyright Copyright &copy; 2009-2015, Store Commander
 * @license commercial
 * All rights reserved! Copying, duplication strictly prohibited
 *
 * *****************************************
 * *           STORE COMMANDER             *
 * *   http://www.StoreCommander.com       *
 * *            V 2015-09-15               *
 * *****************************************
 *
 * Compatibility: PS version: 1.1 to 1.6.1
 *
 **/

$LANG_FF =array(
'Login to your FouleFactory account'=>'Connexion à votre compte FouleFactory'
,'Your ID:'=>'Votre ID :'
,'Your API key:'=>'Votre clé API :'
,'Register and preparing Store Commander'=>'Inscription et préparation de Store Commander'
,'Connecting and preparing'=>'Connexion et préparation'
,'Help: Discover how to boost your store!'=>'Aide : Découvrez comment booster votre boutique !'
,'No account yet?'=>'Pas encore de compte ?'
,'Existing account?'=>'Déjà un compte ?'
,'You need to enter your ID.'=>'Vous devez renseigner votre ID.'
,'You need to enter your API key.'=>'Vous devez renseigner votre clé API.'
,'Working progress'=>'Opération en cours'
,'First project'=>'Premier projet'
,'FouleFactory project management'=>'Gestion des projets FouleFactory'
,'Get prices'=>'Demander les tarifs'
,'Start selected projects'=>'Démarrer projets sélectionnés'
,'Project configuration'=>'Configuration du projet'
,'Enter feature'=>'Saisie caractéristique'
,'Products nb.'=>'Nb. produits'
,'Progress'=>'Progression'
,'Started at'=>'Date démarrage'
,'New project'=>'Nouveau projet'
,'Initialization'=>'Initialisation'
,'Project configuration:'=>'Configuration du projet :'
,'Your question'=>'Votre question'
,'If the result is undefined'=>'Si le résultat est indéterminé'
,'No action'=>'Ne rien faire'
,'Remove the product from its category'=>'Enlever le produit de la catégorie'
,'Associate the product to category'=>'Mettre le produit dans la catégorie'
,'Undefined'=>'Indéterminés'
,'Expected quality result'=>'Qualité du résultat attendu'
,'Good'=>'Bonne'
,'Higher'=>'Supérieure'
,'Excellent'=>'Excellente'
,'Choose'=>'Choisir'
,'Product features to work on'=>'Caractéristique à travailler'
,'Suggested values'=>'Valeurs proposées'
,'Free text answer'=>'Réponse libre'
,'You need to enter your question.'=>'Vous devez renseigner votre question.'
,'You need to enter source(s).'=>'Vous devez renseigner la/les source(s).'
,'Data saved'=>'Données enregistrées'
,'You need to select a feature.'=>'Vous devez renseigner une caractéristique.'
,'You need to select at least one feature value.'=>'Vous devez renseigner au moins une valeur de caractéristique.'
,'FouleFactory Configuration'=>'Configuration FouleFactory'
,'API information'=>'Informations API'
,'Default values'=>'Valeurs par défaut'
,'Gender:'=>'Genre :'
,'Female'=>'Femme'
,'Male'=>'Homme'
,'Firstname:'=>'Prénom :'
,'Name:'=>'Nom :'
,'Email:'=>'Email :'
,'Phone:'=>'Téléphone :'
,'Birthday:'=>'Date de naiss. :'
,'Company:'=>'Société :'
,'Address 1:'=>'Adresse 1 :'
,'Address 2:'=>'Adresse 2 :'
,'City:'=>'Ville :'
,'Postal code:'=>'Code postal :'
,'Country:'=>'Pays :'
,'Mandatory fields'=>'Champs obligatoires'
,'(yyyy-mm-dd)'=>'(aaaa-mm-jj)'
,'You need to enter your gender.'=>'Vous devez renseigner votre sexe.'
,'You need to enter your firstname.'=>'Vous devez renseigner votre prénom.'
,'You need to enter your lastname.'=>'Vous devez renseigner votre nom.'
,'You need to enter your phone.'=>'Vous devez renseigner votre téléphone.'
,'You need to enter your address.'=>'Vous devez renseigner votre adresse.'
,'You need to enter your city.'=>'Vous devez renseigner votre ville.'
,'You need to enter your postal code.'=>'Vous devez renseigner votre code postal.'
,'You need to enter your country.'=>'Vous devez renseigner votre pays.'
,'You need to enter your email.'=>'Vous devez renseigner votre email.'
,'You need to enter your birthday.'=>'Vous devez renseigner votre date de naissance.'
,'You need to enter a valid birthday.'=>'Vous devez renseigner une date de naissance valide.'
,'You need to enter a valid email.'=>'Vous devez renseigner un email valide.'
,'Unselect all'=>'Tout retirer'
,'If the feature value found is not present in the list'=>'Si la valeur de caractéristique trouvée n\'est pas dans la liste proposée'
,'Do not process and don\'t enter the feature'=>'Ne rien faire et ne pas renseigner la caractéristique'
,'Add as feature value'=>'Ajouter comme valeur de caractéristique'
,'Add as customized feature value'=>'Ajouter comme valeur de caractéristique personnalisée'
,'Additionnal instructions'=>'Instructions supplémentaires'
,'The feature to enter is:'=>'La caractéristique à saisir est :'
,'Estimated end date'=>'Date fin estimée'
,'Current project'=>'Projet en cours'
,'Archived'=>'Archivé'
,'Show archived projects'=>'Afficher les projets archivés'
,'Project name ?'=>'Nom du projet ?'
,'To configure'=>'A configurer'
,'To quote'=>'A tarifer'
,'Pay'=>'Payer'
,'Start'=>'Démarrer'
,'Request quote'=>'Demander tarif'
,'Paid'=>'Payé'
,'In progress'=>'En cours'
,'Number of products to process:'=>'Nombre de produits à traiter :'
,'Payment in progress'=>'Paiement en cours'
,'FouleFactory - Project payment'=>'FouleFactory - Paiement du projet'
,'To pay'=>'A payer'
,'Error during last payment'=>'Erreur durant paiement précédent'
,'Archive selected projects'=>'Archiver les projets sélectionnés'
,'Possible values for this features are:'=>'Les valeurs possibles pour cette caractéristique sont :'
,'If the value is not found, enter \'NOTFOUND\'.'=>'En cas de valeur non trouvée, renseignez \'NOTFOUND\'.'
,'Indeterminated'=>'Indéterminés'
,'If your total spending goes over 1000€, please refer to '=>'En cas de dépassement de 1000€ de dépenses cumulées, merci de consulter '
,'this page'=>'cette page'
,'Finished'=>'Terminé'
,'Imported'=>'Importé'
,'Configure'=>'Configurer'
,'Price:'=>'Prix :'
,'Are you sure you want to archive these projects?'=>'Êtes-vous sûr de vouloir archiver ces projets ?'
,'Service only available in France'=>'Service disponible uniquement en France'
,'Currently spent:'=>'Actuellement dépensé :'
,'Use FouleFactory - Store Commander integration to complete your product pages extremely fast.'=>'Utilisez l\'intégration FouleFactory - Store Commander pour renseigner vos fiches produits ultra-rapidement.'
,'Click here to get more information'=>'Cliquez ici pour obtenir plus d\'informations'
,'(free account setup, payment per task)'=>'(création de compte gratuit, paiement à la tâche)'
,'Service currently only available for France.'=>'Service actuellement réservé à la France'
,'FouleFactory enabled'=>'FouleFactory disponible'
,'Possible values:<br/>0: disabled<br/>1: enabled'=>'Valeurs possibles :<br/>0: désactivé<br/>1: activé'
,'Your experience with FouleFactory service'=>'Votre expérience avec le service FouleFactory'
,'The file return_bank.php can\'t be copied in the folder: modules/storecommander. Please check write permissions on this folder.'=>'Le fichier return_bank.php ne peut être copié dans le dossier : modules/storecommander. Veuillez vérifier les droits d\'écriture pour ce dossier.'
,'Create an account'=>'Créer un compte'
,'I subscribe'=>'Je m\'inscris'
,'You must add products in Project Category'=>'Vous devez ajouter des produits dans la catégorie du projet'
,'Description - short'=>'Description - courte'
,'Description - long'=>'Description - longue'
,'Expected description size'=>'Taille de la description souhaitée'
,'50 words'=>'50 mots'
,'100 words'=>'100 mots'
,'150 words'=>'150 mots'
,'250 words'=>'250 mots'
,'350 words'=>'350 mots'
,'500 words'=>'500 mots'
,'750 words'=>'750 mots'
,'10 words'=>'10 mots'
,'20 words'=>'20 mots'
,'30 words'=>'30 mots'
,'Write the short description'=>'Rédiger la description courte'
,'Write the description'=>'Rédiger la description'
,'Write short description'=>'Rédiger la description courte'
,'Write long description'=>'Rédiger la description longue'
,'Your project'=>'Votre projet'
,'All products must be active to be accessible for the workers!'=>'Tous les produits doivent être actifs pour que les fouleurs puissent y accéder !'
,'A short description is limited to '=>'Une description courte est limitée à '
,' characters.'=>' caractères.'
,'Associate products in the category "FouleFactory" > "'=>'Associer les produits dans la catégorie "FouleFactory" > "'
,'" to update the list of products to be handled.'=>'" pour modifier la liste des produits à traiter.'
,'Datas has been successfully imported!'=>'Les données ont été correctement importées !'
);
// ,''=>''

$LANG = array_merge($LANG,$LANG_FF);
?>